locations = ['Paris','Germany','Switzerland','Ireland']
print(locations)
locations.reverse()
print(locations)
print(sorted(locations))
print("They're " + str(len(locations)) + " locations on this list.")
locations.insert(0,'Idaho')
print(locations)
locations.pop()
print(locations)
locations.remove('Idaho')
print(locations)
locations.append('Florida')
print(locations)